name: Update README

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit and push if changed
      run: |
        git add .
        git diff
        git config --global user.email "karunayak63@gmail.com"
        git config --global user.name "KarthikNayak024"
        git commit -m ":wrench: Updated README" -a || echo "No changes to commit"
        git push